@startuml Context
!include <C4/C4_Context>

Person(personAlias, "Клиент", "Подает заявку на подключение домашнего интернета")
System(systemAlias, "Система заявок", "Принимает заявки на подключение домашнего интернета через сайт оператора или мобильное приложение")
System_Ext(geoIpSystemAlias, "Geo IP System", "Система для определения местоположения по IP-адресу или координатам GPS")

Rel(personAlias, systemAlias, "Поиск адреса, проверка возможности подключения, оформление заявки")
Rel_Right(systemAlias, geoIpSystemAlias, "Получить адрес по IP-адресу или координатам GPS")
SHOW_LEGEND()
@enduml
